spring:
  cloud:
    config:
      profile: test
#      label: label-test
      uri: http://localhost:8750/
    rabbitmq:
      host: localhsot
      port: 5672
      username: guest
      password: guest
#      search-paths: dir1
#      server:
#        git:
#          search-paths: dir1
#    discovery:
#      enable: true
#      serviceId: ms-platform-config-server
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
#management:
#  security:
#    enabled: false
eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    prefer-ip-address: true
#        ip-address: 127.0.0.1
  client:
    serviceUrl:
#            defaultZone: http://192.168.103.28:8761/eureka/
                    # docker 部署开启
      defaultZone: http://192.168.98.195:1111/eureka/
management:
  security:
    enabled: false